parameters:
- name: "artifactName"
  type: string

jobs:
- job: BuildJob
  displayName: 'Build Job'
  pool:
    vmImage: 'ubuntu-latest' 
  steps:
  - task: NodeTool@1
  inputs:
      version: '20.x'
  displayName: 'Install Node.js'
  - script: |
      npm install
  displayName: 'npm install'
  - script: |
      npm run build
  displayName: 'npm run build'
  - script: |
      npm run package
  displayName: 'npm run package'
  - script: |
      npm run test
  displayName: 'npm run test'
  - task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'dist'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/dist.zip'
    replaceExistingArchive: true
  - task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.ArtifactStagingDirectory)'
    contents: 'dist.zip'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy project files'
  - task: PublishPipelineArtifact@1
  inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)/dist.zip'
      artifactName: ${{ parameters.artifactName }}
      publishLocation: 'pipeline'
  displayName: 'Publish npm artifact'