parameters:
  - name: "serviceName"
    type: string

jobs:
  - job: TerraformJob
    displayName: "Terraform Job"
    pool:
      vmImage: 'ubuntu-latest'
      steps:
      - script: |
        echo "Running Terraform init..."
        terraform init
      displayName: 'Terraform init'
      env:
          TF_STATE_BLOB_ACCOUNT_NAME:



        echo "Running Terraform plan..."
        terraform plan -var-file ${{ parameters.tfvarsFile }}
      displayName: 'Terraform init'
      - script: |
        echo "Running Terraform init..."
        terraform init
        echo "Running Terraform plan..."
        terraform plan -var-file ${{ parameters.tfvarsFile }}
      displayName: 'Terraform init'
      
